name: Deploy Node.js to VPS

on:
  push:
    branches:
      - main   # đổi nếu bạn dùng branch khác

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd SEJobs-Backend
            git pull origin main
            npm install --production
            pm2 restart se-jobs || pm2 start npm --name "se-jobs" -- start
          EOF 